begin;

create table if not exists public.incident_recipients (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.incidents(id) on delete cascade,
  relationship_id uuid references public.guardian_relationships(id) on delete set null,
  guardian_user_id uuid references public.profiles(id) on delete set null,
  guardian_name text not null,
  guardian_phone text,
  is_primary boolean not null default false,
  push_status text not null default 'pending'
    check (push_status in ('not_applicable', 'pending', 'delivered', 'failed')),
  sms_status text not null default 'pending'
    check (sms_status in ('not_configured', 'pending', 'sent', 'failed', 'skipped')),
  escalation_status text not null default 'waiting'
    check (escalation_status in ('waiting', 'not_needed', 'sent', 'failed')),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (incident_id, relationship_id)
);

create index if not exists incident_recipients_incident_idx
  on public.incident_recipients(incident_id, is_primary desc, created_at);

create table if not exists public.incident_escalation_events (
  id bigint generated by default as identity primary key,
  incident_id uuid not null references public.incidents(id) on delete cascade,
  level integer not null default 0 check (level between 0 and 5),
  kind text not null check (kind in ('initial_delivery', 'guardian_timeout', 'emergency_call_handoff', 'responder_simulation')),
  status text not null check (status in ('pending', 'completed', 'partial', 'failed', 'simulated')),
  message text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists one_guardian_timeout_escalation_per_incident
  on public.incident_escalation_events(incident_id, kind)
  where kind = 'guardian_timeout';
create index if not exists incident_escalation_events_incident_idx
  on public.incident_escalation_events(incident_id, created_at);

drop trigger if exists incident_recipients_set_updated_at on public.incident_recipients;
create trigger incident_recipients_set_updated_at before update on public.incident_recipients
for each row execute function private.set_updated_at();

alter table public.incident_recipients enable row level security;
alter table public.incident_escalation_events enable row level security;

drop policy if exists incident_recipients_read_allowed on public.incident_recipients;
create policy incident_recipients_read_allowed on public.incident_recipients for select to authenticated
using (
  guardian_user_id = (select auth.uid())
  or private.owns_incident(incident_id, (select auth.uid()))
);

drop policy if exists incident_escalation_events_read_allowed on public.incident_escalation_events;
create policy incident_escalation_events_read_allowed on public.incident_escalation_events for select to authenticated
using (
  private.owns_incident(incident_id, (select auth.uid()))
  or private.is_assigned_guardian(incident_id, (select auth.uid()))
);

create or replace function public.assign_incident_guardians(target_incident_id uuid)
returns setof public.incident_guardians
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id uuid;
begin
  select user_id into owner_id from public.incidents
  where id = target_incident_id and status = 'active';
  if owner_id is null or owner_id <> auth.uid() then raise exception 'NOT_INCIDENT_OWNER'; end if;

  insert into public.incident_guardians(incident_id, guardian_user_id)
  select target_incident_id, guardian_user_id
  from public.guardian_relationships
  where protected_user_id = owner_id
    and guardian_user_id is not null
    and status = 'accepted'
  on conflict (incident_id, guardian_user_id) do nothing;

  insert into public.incident_recipients(
    incident_id,
    relationship_id,
    guardian_user_id,
    guardian_name,
    guardian_phone,
    is_primary,
    push_status,
    sms_status
  )
  select
    target_incident_id,
    id,
    guardian_user_id,
    guardian_name,
    guardian_phone,
    is_primary,
    case when guardian_user_id is null then 'not_applicable' else 'pending' end,
    case when nullif(trim(guardian_phone), '') is null then 'not_configured' else 'pending' end
  from public.guardian_relationships
  where protected_user_id = owner_id
    and status in ('pending', 'accepted')
    and (guardian_user_id is not null or nullif(trim(guardian_phone), '') is not null)
  on conflict (incident_id, relationship_id) do nothing;

  return query select * from public.incident_guardians where incident_id = target_incident_id;
end;
$$;

create or replace function public.record_emergency_call_handoff(target_incident_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not private.owns_incident(target_incident_id, auth.uid()) then
    raise exception 'NOT_INCIDENT_OWNER';
  end if;
  insert into public.incident_escalation_events(incident_id, level, kind, status, message)
  values (target_incident_id, 0, 'emergency_call_handoff', 'completed', 'Emergency dialer opened by the protected user. Call completion is not confirmed.');
end;
$$;

create or replace function public.record_responder_simulation(target_incident_id uuid, simulated_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  is_demo_incident boolean;
begin
  select is_demo into is_demo_incident from public.incidents
  where id = target_incident_id and user_id = auth.uid();
  if is_demo_incident is null then raise exception 'NOT_INCIDENT_OWNER'; end if;
  if not is_demo_incident then raise exception 'DEMO_INCIDENT_REQUIRED'; end if;
  if simulated_status not in ('received', 'reviewing', 'dispatched_simulation', 'closed') then
    raise exception 'INVALID_SIMULATION_STATUS';
  end if;
  insert into public.incident_escalation_events(incident_id, level, kind, status, message)
  values (
    target_incident_id,
    0,
    'responder_simulation',
    'simulated',
    'Hackathon responder simulation: ' || replace(simulated_status, '_', ' ') || '. No police or emergency service was contacted.'
  );
end;
$$;

revoke all on public.incident_recipients from anon, authenticated;
revoke all on public.incident_escalation_events from anon, authenticated;
grant select on public.incident_recipients to authenticated;
grant select on public.incident_escalation_events to authenticated;
grant execute on function public.record_emergency_call_handoff(uuid) to authenticated;
grant execute on function public.record_responder_simulation(uuid, text) to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.incident_recipients;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.incident_escalation_events;
exception when duplicate_object then null;
end $$;

commit;
